import { createCollection } from '../createCollection';

// Inspired by https://design.ubuntu.com/brand/colour-palette; adapted for app contrast and light/dark surfaces.
export const ubuntu = createCollection({
  primary: '#AC3E15',
  onPrimary: '#FFFFFF',
  primaryContainer: '#FFDCCB',
  onPrimaryContainer: '#3C1000',
  secondary: '#772953',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#FFD8EB',
  onSecondaryContainer: '#350D25',
  tertiary: '#5E2750',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#FAD7ED',
  onTertiaryContainer: '#2D0C25',
  background: '#F6F3F1',
  onBackground: '#2C2428',
  surface: '#FFFFFF',
  onSurface: '#2C2428',
  surfaceVariant: '#EDE0E6',
  onSurfaceVariant: '#54434D',
  outline: '#85717E',
  outlineVariant: '#D8C2CE',
}, {
  primary: '#FF996B',
  onPrimary: '#401600',
  primaryContainer: '#733017',
  onPrimaryContainer: '#FFDDCB',
  secondary: '#E9A7D1',
  onSecondary: '#39132C',
  secondaryContainer: '#5E2750',
  onSecondaryContainer: '#FFD8EB',
  tertiary: '#CFA0D8',
  onTertiary: '#341439',
  tertiaryContainer: '#54245C',
  onTertiaryContainer: '#F9D8FF',
  background: '#1C111A',
  onBackground: '#F5E8EF',
  surface: '#2C1A28',
  onSurface: '#F5E8EF',
  surfaceVariant: '#48313F',
  onSurfaceVariant: '#DDC3D2',
  outline: '#AB8E9F',
  outlineVariant: '#604653',
});
